SELECT
    SCHEDULE_ID AS ACTIVITY_ID,
    EVENT_TYPE_ID,
    CASE
        WHEN EVENT_TYPE_ID = 1 THEN 'Training'
        WHEN EVENT_TYPE_ID = 2 THEN 'Meeting'
        WHEN EVENT_TYPE_ID = 4 THEN 'Other'
        WHEN EVENT_TYPE_ID = 5 THEN 'Competition'
        WHEN EVENT_TYPE_ID = 6 THEN 'Cup'
        WHEN EVENT_TYPE_ID = 7 THEN 'Match'
        WHEN EVENT_TYPE_ID = 9 THEN 'Work Shift'
    END AS EVENT_TYPE_LABEL,
    CONCAT(SCHEDULE_DATE, ' ', START_TIME, ':00 Europe/Stockholm')::TIMESTAMPTZ AS START_AT,
    CONCAT(SCHEDULE_DATE, ' ', END_TIME, ':00 Europe/Stockholm')::TIMESTAMPTZ AS END_AT,
    DATE_DIFF('minute', START_AT, END_AT) AS DURATION_MINUTES,
    PLACE,
    IS_HOME_FACILITY,
    OPPONENT_CLUB_ID,
    OPPONENT,
    RESULT_ID,
    CASE
        WHEN RESULT_ID = 1 THEN 'Loss'
        WHEN RESULT_ID = 2 THEN 'Draw'
        WHEN RESULT_ID = 3 THEN 'Win'
    END AS RESULT_LABEL,
    GOALS_FOR,
    GOALS_AGAINST
FROM {{ ref('stg_activity') }}
