SELECT
    MD5(
        CONCAT(IFNULL(SCHEDULE_ID::VARCHAR, ''), IFNULL(USER_ID::VARCHAR, ''))
    ) AS ATTENDANCE_ID,
    SCHEDULE_ID AS ACTIVITY_ID,
    USER_ID AS MEMBER_ID
FROM {{ ref('stg_presence') }}
