SELECT
    USER_ID AS MEMBER_ID,
    IFNULL(NULLIF(FIRST_NAME, ''), '<DELETED>') AS FIRST_NAME,
    IFNULL(NULLIF(LAST_NAME, ''), '<DELETED>') AS LAST_NAME,
    TEAM_NAME,
    INACTIVATED_AT,
    DATE_OF_BIRTH,
    IS_LEADER,
    IS_PLAYER,
    MEMBER_TYPE_ID,
    CASE
        WHEN MEMBER_TYPE_ID = 4 THEN 'Parent'
        WHEN MEMBER_TYPE_ID = 2 THEN 'Leader'
        WHEN MEMBER_TYPE_ID = 1 THEN 'Player'
    END AS MEMBER_TYPE_LABEL
FROM {{ ref('stg_presence') }}
QUALIFY ROW_NUMBER() OVER (PARTITION BY USER_ID ORDER BY SCHEDULE_ID DESC) = 1
