SELECT
    USER_ID AS MEMBER_ID,
    IFNULL(NULLIF(FIRST_NAME, ''), '<DELETED>') AS FIRST_NAME,
    IFNULL(NULLIF(LAST_NAME, ''), '<DELETED>') AS LAST_NAME,
    TEAM_NAME,
    INACTIVATED_AT,
    DATE_OF_BIRTH,
    IS_LEADER,
    IS_PLAYER
FROM {{ ref('stg_presence') }}
QUALIFY ROW_NUMBER() OVER (PARTITION BY USER_ID ORDER BY SCHEDULE_ID DESC) = 1
