SELECT
    USER_ID AS MEMBER_ID,
    IFNULL(NULLIF(FIRST_NAME, ''), '<DELETED>') AS FIRST_NAME,
    IFNULL(NULLIF(LAST_NAME, ''), '<DELETED>') AS LAST_NAME,
    TEAM_NAME,
    INACTIVATED_AT,
    DATE_OF_BIRTH,
    MEMBER_TYPE_ID,
    member_type.NAME AS MEMBER_TYPE
FROM {{ ref('stg_presence') }}
LEFT JOIN {{ ref('member_type') }} USING(MEMBER_TYPE_ID)
QUALIFY ROW_NUMBER() OVER (PARTITION BY USER_ID ORDER BY SCHEDULE_ID DESC) = 1
