version: 2

models:
  - name: player_status
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - date_day
            - member_id
    columns:
      - name: date_day
        data_tests:
          - not_null
      - name: member_id
        data_tests:
          - not_null
      - name: status
        data_tests:
          - not_null
          - accepted_values:
              values: ['Active', 'Churned']
      - name: status_event
        data_tests:
          - accepted_values:
              values: [ 'New', 'Churn' ]
  - name: activity
    description: Team activities
    columns:
      - name: activity_id
        data_tests:
          - unique
          - not_null
      - name: activity
        data_tests:
          - not_null
      - name: result
        data_tests:
          - not_null:
              config:
                where: 'RESULT_TYPE_ID IS NOT NULL'
      - name: start_at
        data_tests:
          - not_null
      - name: end_at
        data_tests:
          - not_null
      - name: duration_minutes
        data_tests:
          - not_null
      - name: duration_hours
        data_tests:
          - not_null
  - name: member
    description: Team members
    columns:
      - name: member_id
        data_tests:
          - unique
          - not_null
      - name: first_name
        data_tests:
          - not_null
      - name: last_name
        data_tests:
          - not_null
      - name: birth_date
      - name: member_type
        data_tests:
          - not_null
      - name: full_name
        data_tests:
          - not_null
          - unique
  - name: attended_activity
    description: A member attended an activity
    columns:
      - name: attendance_id
        data_tests:
          - unique
          - not_null
      - name: member_id
        data_tests:
          - not_null
      - name: activity_id
        data_tests:
          - not_null
  - name: export_all
    description: Wide table consisting of all attendances and the related data
